cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/versions'

brew 'coreutils'
brew 'docker-machine'
brew 'docker-machine-driver-xhyve'
brew 'htop'
brew 'openssl'
brew 'postgresql'
brew 'python'
brew 'python3'
brew 'redis'
brew 'xz'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'skype'
cask 'spectacle'
cask 'sublime-text3'
cask 'transmission'
cask 'vlc'
