#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# Run Homebrew through the Brewfile
brew tap 'homebrew/bundle'
echo "› brew bundle"
brew bundle
