#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# Run Homebrew through the Brewfile
brew tap 'homebrew/bundle'
echo "› brew bundle"
brew bundle

# install bg-r46 keyboard layout
curl --fail http://apple-blogger.ru/wp-content/uploads/2013/03/russian_kb_layout.zip -o russian_kb_layout.zip \
    && unzip russian_kb_layout.zip \
    && sudo mv russian_keylayout/* /Library/Keyboard\ Layouts \
    && rm -fr russian_kb_layout.zip russian_keylayout
